name: Build Check

on:
  push:
    branches: [main, develop, chroe-workflow-setup]
  pull_request:
    branches: [main, develop, chroe-workflow-setup]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format
